trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  storageAccountName: poc33   # change if your storage name is different

steps:
- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'   # your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Uploading files to Azure Blob..."

      az storage blob upload-batch \
        --account-name ${{ variables.storageAccountName }} \
        --destination '$web' \
        --source . \
        --overwrite